### ISSUE TITLE
Implement Splash Screen

### ISSUE THREAD

**Issue by acmjec** [acmjec/Hacktoberfest2023-Android_7_Min_Workout#4]
Implement Splash Screen Inside app which shows APP icon with Animation and then automatically switch to main activity.

**Comment by githubashutoshsoni** [comment]
Can you assign this to me?

**Comment by acmjec** [comment]
Sure! we will assign this issue to you once we register this Repository with Hacktoberfest.

**Comment by acmjec** [comment]
@Maan-Sharma and @githubashutoshsoni. I have assigned this issue to both of you. Start Contributing. Happy Hacking!!

**Comment by Maan-Sharma** [comment]
hey, I added the feature !!! and also I made a PR @acmjec

**Comment by acmjec** [comment]
Good Job @Maan-Sharma ! Merged your PR. Keep Contributing.
